### ISSUE TITLE
Can you provide a more detailed test requirement, thank you.

### ISSUE THREAD

**Issue by nffxgln** [clelouch/AFNet#2]
I am testing the AFNET model on ReDWeb-S, COME-E, and COME-H datasets, but it failed when loading the AFNet_epoch_best.pth. 
The EOFError: Ran out of input. I don't know how to fix this bug, can you help me fix this bug? Thank you very much.

**Comment by clelouch** [comment]
I just try to reload the checkpoint and not error is reported. If you use pycharm, you can check whether required packages are installed.

If you still have this problem, it might be better to give a detailed description about the error. Otherwise, i cannot find the solution.

**Comment by nffxgln** [comment]
The version of torch is 1.7.1, torchvision  is 0.8.2. Can you give me a detailed requirement. 
![1681721425640](https://user-images.githubusercontent.com/52684755/232434365-7258d6a3-62ec-4e16-ac32-bbde066af697.png)

**Comment by clelouch** [comment]
Have you downloaded the pretrained weight?

I found a similar mistake.
> https://github.com/hsinyuan-huang/FlowQA/issues/17

**Comment by nffxgln** [comment]
Thank you for your patience. I downloaded the pretrained weight. The mistake was fixed.

**Comment by g0ldata** [comment]
@nffxgln - where did you find the pretrained weights? I have not been able to find a usable version of wmtlstm-b142a7f2.pth.
