### ISSUE TITLE
Could not start the training

### ISSUE THREAD

**Issue by ariharasudhanm** [clelouch/AFNet#3]
In the file train.py while loading the model resnet50+vit_16(imagenet21k_R50+ViT-B_16.npz) I am getting 
KeyError: 'Transformer/encoderblock_0\\MultiHeadDotProductAttention_1/query\\kernel is not a file in the archive'

I manually downloaded the model from google bucket.

**Comment by clelouch** [comment]
Did you put the model in the correct directory?

**Comment by LiviMava** [comment]
> In the file train.py while loading the model resnet50+vit_16(imagenet21k_R50+ViT-B_16.npz) I am getting KeyError: 'Transformer/encoderblock_0\MultiHeadDotProductAttention_1/query\kernel is not a file in the archive'
> 
> I manually downloaded the model from google bucket.

May I ask if it has been resolved? I also have this problem

**Comment by LiviMava** [comment]
https://blog.csdn.net/plmm__/article/details/132911163?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522169519155616800215023796%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=169519155616800215023796&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_ecpm_v1~rank_v31_ecpm-5-132911163-null-null.142^v94^insert_down1&utm_term=KeyError%3A%20Transformer%2Fencoderblock_0%5C%5CMultiHeadDotProductAttention_1%2Fquery%5C%5Ckernel%20is%20not%20a%20file%20in%20the%20archive&spm=1018.2226.3001.4187
