### ISSUE TITLE
Pretrained model on imagenet

### ISSUE THREAD

**Issue by ziskazuo** [clelouch/AFNet#4]
Hi sir, when i train this model, i met some mistakes. i wonder where I  can get the pretrained model named "imagenet21k_R50+ViT-B_16.npz"?i can't find any statetment in <README>。“imagenet21k_R50+ViT-B_16.npz” is written in model.py line 157. i try to download a "R50+ViT-B_16.npz" on github,but something wrong occured when run. and i don't know if there is any pretrained model needed to be loaded when train, can y  offer some help?                                      THANK YOU VERY MUCH.

**Comment by clelouch** [comment]
Thanks for your interest in our work. We have uploaded “imagenet21k_R50+ViT-B_16.npz” and the link is provided on the main page.
